export const EXERCISE_DETAILS = {
  'Barbell Bench Press': {
    type: 'push',
    muscles: ['Chest', 'Shoulders', 'Triceps'],
    difficulty: 'Intermediate',
    description: 'Lie on a flat bench, lower the barbell to your chest, then press it back up.',
    steps: [
      'Lie flat on bench, feet planted on floor, retract shoulder blades',
      'Grip bar slightly wider than shoulder-width',
      'Unrack the bar and hold it directly above your shoulders',
      'Lower the bar slowly to your mid-chest, elbows at 45°',
      'Press the bar back up explosively to starting position',
    ],
    tips: 'Keep your wrists straight and don\'t bounce the bar off your chest. Breathe in on the way down, out on the way up.',
    commonMistakes: 'Flaring elbows too wide, bouncing bar off chest, lifting shoulders off bench.',
    duration: 45, rest: 90,
  },
  'Dumbbell Flyes': {
    type: 'fly',
    muscles: ['Chest'],
    difficulty: 'Beginner',
    description: 'Lie on a bench with dumbbells extended above you, then lower arms out to sides in an arc motion.',
    steps: ['Lie on flat bench holding dumbbells above chest with slight bend in elbows', 'Lower arms out to sides in a wide arc until you feel a stretch', 'Squeeze chest to bring dumbbells back together at the top'],
    tips: 'Keep a slight bend in your elbows throughout. Don\'t go too heavy — form matters more than weight.',
    commonMistakes: 'Bending elbows too much (turns into press), going too heavy, dropping arms too low.',
    duration: 45, rest: 60,
  },
  'Incline Dumbbell Press': {
    type: 'push',
    muscles: ['Upper Chest', 'Shoulders'],
    difficulty: 'Intermediate',
    description: 'Similar to flat bench press but on an incline to target the upper chest.',
    steps: ['Set bench to 30-45° incline', 'Press dumbbells up from chest level', 'Lower with control and repeat'],
    tips: 'Don\'t set the incline too high or it becomes a shoulder exercise. Keep elbows at 45°.',
    commonMistakes: 'Incline too steep, flaring elbows, arching back excessively.',
    duration: 45, rest: 75,
  },
  'Push-ups': {
    type: 'push',
    muscles: ['Chest', 'Shoulders', 'Triceps', 'Core'],
    difficulty: 'Beginner',
    description: 'Classic bodyweight exercise targeting chest, shoulders and triceps.',
    steps: ['Start in plank position with hands slightly wider than shoulders', 'Lower your body until chest nearly touches the floor', 'Push back up to starting position keeping body straight'],
    tips: 'Keep your body in a straight line from head to heels. Don\'t sag your hips.',
    commonMistakes: 'Sagging hips, flaring elbows, not going low enough, holding breath.',
    duration: 30, rest: 45,
  },
  'Cable Crossover': {
    type: 'fly',
    muscles: ['Chest'],
    difficulty: 'Beginner',
    description: 'Stand between two cable pulleys and bring your hands together in front of you.',
    steps: ['Set pulleys to high position, grab handles and step forward', 'Lean slightly forward with one foot ahead', 'Bring handles down and together in front of your chest, squeezing', 'Slowly return to start'],
    tips: 'Keep a slight bend in your elbows. Focus on the squeeze at the bottom.',
    commonMistakes: 'Using too much weight, bending too far forward, using arms instead of chest.',
    duration: 45, rest: 60,
  },
  'Overhead Dumbbell Press': {
    type: 'press',
    muscles: ['Shoulders', 'Triceps'],
    difficulty: 'Intermediate',
    description: 'Sit or stand and press dumbbells from shoulder height to overhead.',
    steps: ['Hold dumbbells at shoulder height, palms forward', 'Press dumbbells overhead until arms are extended', 'Lower back to shoulders with control'],
    tips: 'Keep your core tight. Don\'t arch your back excessively. Stop if you feel shoulder pain.',
    commonMistakes: 'Arching back excessively, using momentum, not locking out at top.',
    duration: 45, rest: 75,
  },
  'Lateral Raises': {
    type: 'raise',
    muscles: ['Side Delts'],
    difficulty: 'Beginner',
    description: 'Stand holding light dumbbells and raise them out to your sides.',
    steps: ['Stand with dumbbells at your sides, slight bend in elbows', 'Raise arms out to sides until parallel to floor', 'Lower slowly back to starting position'],
    tips: 'Use light weight and focus on form. Lead with your elbows, not your hands.',
    commonMistakes: 'Using momentum, raising too high, bending wrists, using too much weight.',
    duration: 40, rest: 45,
  },
  'Front Raises': {
    type: 'raise',
    muscles: ['Front Delts'],
    difficulty: 'Beginner',
    description: 'Raise dumbbells in front of you to shoulder height.',
    steps: ['Stand with dumbbells in front of thighs, palms facing you', 'Raise arms forward to shoulder height', 'Lower with control'],
    tips: 'Keep your body still — don\'t swing. Control the descent.',
    commonMistakes: 'Swinging the weight, raising too high, leaning back.',
    duration: 40, rest: 45,
  },
  'Face Pulls': {
    type: 'pull',
    muscles: ['Rear Delts', 'Upper Back'],
    difficulty: 'Beginner',
    description: 'Pull a cable or band toward your face to target rear shoulders and upper back.',
    steps: ['Set cable pulley to upper-chest height with rope attachment', 'Grip rope with both hands, step back', 'Pull rope toward your face, separating the ends', 'Slowly return to start'],
    tips: 'Keep elbows high. Focus on squeezing your upper back at the peak.',
    commonMistakes: 'Using too much weight, pulling to chin instead of face, not separating ends.',
    duration: 45, rest: 45,
  },
  'Tricep Pushdown': {
    type: 'push',
    muscles: ['Triceps'],
    difficulty: 'Beginner',
    description: 'Push a cable bar down using only your triceps.',
    steps: ['Attach straight bar to high cable pulley', 'Grip bar with hands shoulder-width apart, elbows at sides', 'Push bar down until arms are fully extended', 'Slowly return to 90°'],
    tips: 'Keep your elbows glued to your sides. Only your forearms should move.',
    commonMistakes: 'Moving elbows, leaning over the bar, using shoulders instead of triceps.',
    duration: 40, rest: 45,
  },
  'Overhead Tricep Extension': {
    type: 'press',
    muscles: ['Triceps'],
    difficulty: 'Intermediate',
    description: 'Extend a dumbbell overhead by straightening your arms.',
    steps: ['Hold one dumbbell with both hands overhead, arms bent', 'Lower dumbbell behind your head by bending elbows', 'Extend arms to return to start'],
    tips: 'Keep elbows pointing forward and close to your head. Control the movement.',
    commonMistakes: 'Flaring elbows out, using too much weight, not extending fully.',
    duration: 40, rest: 60,
  },
  'Close-Grip Bench Press': {
    type: 'push',
    muscles: ['Triceps', 'Inner Chest'],
    difficulty: 'Intermediate',
    description: 'Bench press with hands close together to emphasize triceps.',
    steps: ['Lie on flat bench, grip barbell with hands shoulder-width apart', 'Lower bar to lower chest', 'Press back up focusing on triceps'],
    tips: 'Keep elbows close to your body throughout.',
    commonMistakes: 'Grip too narrow (wrist strain), flaring elbows.',
    duration: 45, rest: 75,
  },
  'Deadlifts': {
    type: 'hinge',
    muscles: ['Hamstrings', 'Glutes', 'Lower Back', 'Core'],
    difficulty: 'Advanced',
    description: 'Lift a barbell from the floor by driving through your legs and extending your hips.',
    steps: ['Stand with feet hip-width, bar over midfoot', 'Bend at hips and knees to grip the bar', 'Keep back flat, chest up, brace core', 'Drive through heels to stand up straight with the bar', 'Lower bar back to floor with control'],
    tips: 'Keep the bar close to your body. Your back must stay neutral — never round it.',
    commonMistakes: 'Rounding the back, jerking the bar, looking up (keep neck neutral), not using leg drive.',
    duration: 50, rest: 120,
  },
  'Pull-ups / Lat Pulldown': {
    type: 'pull',
    muscles: ['Lats', 'Biceps', 'Upper Back'],
    difficulty: 'Intermediate',
    description: 'Pull yourself up to a bar or pull a bar down to your chest.',
    steps: ['Grip bar wider than shoulder-width, palms facing away', 'Pull yourself up until chin clears the bar (or bar to upper chest for pulldown)', 'Lower with control', 'For pulldown: pull bar to upper chest, squeeze lats'],
    tips: 'Don\'t use momentum. Squeeze your shoulder blades together at the bottom.',
    commonMistakes: 'Swinging body, not going full range, using chin over bar with poor form.',
    duration: 45, rest: 90,
  },
  'Bent Over Rows': {
    type: 'pull',
    muscles: ['Upper Back', 'Lats', 'Biceps'],
    difficulty: 'Intermediate',
    description: 'Hinge forward and pull a barbell or dumbbells to your lower ribcage.',
    steps: ['Stand with feet hip-width, hinge at hips until torso is nearly parallel to floor', 'Let the bar hang at knee level', 'Pull the bar to your lower ribcage, squeezing shoulder blades', 'Lower with control'],
    tips: 'Keep your back flat. Don\'t use momentum — control the weight.',
    commonMistakes: 'Rounding the back, using momentum, pulling too high, standing up too straight.',
    duration: 45, rest: 75,
  },
  'Seated Cable Rows': {
    type: 'pull',
    muscles: ['Upper Back', 'Lats'],
    difficulty: 'Beginner',
    description: 'Sit and pull a cable handle toward your torso.',
    steps: ['Sit at cable row station, feet on platform, slight bend in knees', 'Grasp handle with arms extended', 'Pull handle to your stomach, squeezing shoulder blades', 'Slowly extend arms back'],
    tips: 'Keep your back straight. Don\'t lean too far back. Squeeze at the peak.',
    commonMistakes: 'Using too much body lean, rounding shoulders, jerking the weight.',
    duration: 45, rest: 60,
  },
  'Dumbbell Rows': {
    type: 'pull',
    muscles: ['Upper Back', 'Lats', 'Biceps'],
    difficulty: 'Beginner',
    description: 'Support yourself on a bench and row a dumbbell up.',
    steps: ['Place one knee and same-side hand on a bench', 'Hold dumbbell in other hand, arm hanging down', 'Pull dumbbell to your hip, squeezing your back', 'Lower with control'],
    tips: 'Keep your back parallel to the floor. Pull to your hip, not your armpit.',
    commonMistakes: 'Rotating the torso, using momentum, not going full range.',
    duration: 45, rest: 60,
  },
  'Barbell Curls': {
    type: 'curl',
    muscles: ['Biceps'],
    difficulty: 'Beginner',
    description: 'Curl a barbell up using only your biceps.',
    steps: ['Stand with barbell in hands, palms facing up, elbows at sides', 'Curl the bar up toward your shoulders', 'Squeeze at the top, then lower slowly'],
    tips: 'Don\'t swing your body. Keep your elbows pinned to your sides.',
    commonMistakes: 'Using momentum, moving elbows forward, not lowering fully.',
    duration: 40, rest: 60,
  },
  'Dumbbell Hammer Curls': {
    type: 'curl',
    muscles: ['Biceps', 'Forearms'],
    difficulty: 'Beginner',
    description: 'Curl dumbbells with palms facing each other to target the brachialis.',
    steps: ['Hold dumbbells at sides with palms facing each other', 'Curl weight up toward shoulders keeping palms in', 'Lower with control'],
    tips: 'Keep your wrists neutral (thumbs up) throughout.',
    commonMistakes: 'Rotating wrists, using momentum, not going full range.',
    duration: 40, rest: 60,
  },
  'Preacher Curls': {
    type: 'curl',
    muscles: ['Biceps'],
    difficulty: 'Intermediate',
    description: 'Curl a bar on a preacher bench to eliminate momentum.',
    steps: ['Sit at preacher bench with upper arms on the pad', 'Grip EZ-bar with palms up', 'Curl bar up toward shoulders', 'Lower slowly without fully extending'],
    tips: 'Don\'t hyperextend at the bottom. Keep your upper arms pressed into the pad.',
    commonMistakes: 'Lifting elbows off pad, using momentum, not full range.',
    duration: 40, rest: 60,
  },
  'Barbell Squats': {
    type: 'squat',
    muscles: ['Quads', 'Hamstrings', 'Glutes', 'Core'],
    difficulty: 'Intermediate',
    description: 'The king of exercises — squat with a barbell on your back.',
    steps: ['Set bar on upper back (not neck), grip bar', 'Stand with feet shoulder-width, toes slightly out', 'Brace core, push hips back, and bend knees to lower', 'Go to parallel or below, then drive up through heels'],
    tips: 'Keep your chest up and back tight. Knees should track over toes. Go as deep as your mobility allows.',
    commonMistakes: 'Rounding lower back (butt wink), knees caving in, heels lifting, not going deep enough.',
    duration: 50, rest: 120,
  },
  'Romanian Deadlifts': {
    type: 'hinge',
    muscles: ['Hamstrings', 'Glutes', 'Lower Back'],
    difficulty: 'Intermediate',
    description: 'A hip-hinge movement targeting the posterior chain.',
    steps: ['Hold barbell at hip height, feet hip-width, slight bend in knees', 'Push hips back and slide bar down your thighs', 'Feel the stretch in hamstrings, then drive hips forward to return'],
    tips: 'Keep a flat back. The bar stays in contact with your legs. Don\'t round at the bottom.',
    commonMistakes: 'Rounding the back, bending knees too much (turns into squat), bar drifting away.',
    duration: 45, rest: 90,
  },
  'Leg Press': {
    type: 'push',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    difficulty: 'Beginner',
    description: 'Push a weighted platform away using your legs.',
    steps: ['Sit in leg press machine, feet shoulder-width on platform', 'Lower platform by bending knees to 90°', 'Press through heels to extend legs without locking knees'],
    tips: 'Don\'t lock your knees at the top. Keep your lower back pressed into the seat.',
    commonMistakes: 'Locking knees, going too deep (butt lifts off seat), heels lifting.',
    duration: 50, rest: 90,
  },
  'Walking Lunges': {
    type: 'lunge',
    muscles: ['Quads', 'Glutes', 'Hamstrings'],
    difficulty: 'Intermediate',
    description: 'Step forward into a lunge and alternate legs while walking.',
    steps: ['Stand with feet together, hands on hips or holding dumbbells', 'Step forward with right leg and lower until both knees bend 90°', 'Push off back foot and bring it forward into the next lunge'],
    tips: 'Keep your torso upright. Front knee should stay above ankle, not past toes.',
    commonMistakes: 'Knee going past toes, leaning forward, short steps, wobbling.',
    duration: 45, rest: 60,
  },
  'Leg Extensions': {
    type: 'push',
    muscles: ['Quads'],
    difficulty: 'Beginner',
    description: 'Extend your legs on a machine to isolate the quadriceps.',
    steps: ['Sit in leg extension machine, pad on shins', 'Extend legs until straight (not locked)', 'Squeeze quads at top, lower with control'],
    tips: 'Don\'t lock your knees. Squeeze at the top for maximum contraction.',
    commonMistakes: 'Locking knees, using momentum, bouncing the weight.',
    duration: 40, rest: 45,
  },
  'Leg Curls': {
    type: 'curl',
    muscles: ['Hamstrings'],
    difficulty: 'Beginner',
    description: 'Curl your legs toward your glutes on a machine.',
    steps: ['Lie face down on leg curl machine, pad behind ankles', 'Curl legs toward glutes', 'Lower with control without letting weight touch the stack'],
    tips: 'Keep your hips pressed into the pad. Squeeze at the peak.',
    commonMistakes: 'Lifting hips off pad, using momentum, not full range.',
    duration: 40, rest: 45,
  },
  'Calf Raises': {
    type: 'raise',
    muscles: ['Calves'],
    difficulty: 'Beginner',
    description: 'Raise your heels to target the calf muscles.',
    steps: ['Stand on a step or platform with heels hanging off', 'Lower heels below the step for a stretch', 'Push up onto toes as high as possible', 'Hold at top for a second, then lower',
    ],
    tips: 'Go for full range of motion. Slow and controlled. Add weight when bodyweight gets easy.',
    commonMistakes: 'Partial range of motion, bouncing, rushing the reps.',
    duration: 40, rest: 45,
  },
  'Plank': {
    type: 'hold',
    muscles: ['Core', 'Shoulders', 'Glutes'],
    difficulty: 'Beginner',
    description: 'Hold a straight-body position on your forearms and toes.',
    steps: ['Start on forearms and toes, body in a straight line', 'Engage core and glutes, don\'t let hips sag', 'Hold position while breathing steadily'],
    tips: 'Keep your body in a straight line from head to heels. Push the floor away with your elbows.',
    commonMistakes: 'Sagging hips, raising butt too high, holding breath, looking up.',
    duration: 30, rest: 30,
  },
  'Cable Crunches': {
    type: 'crunch',
    muscles: ['Upper Abs'],
    difficulty: 'Beginner',
    description: 'Crunch down against cable resistance to target upper abs.',
    steps: ['Attach rope to high pulley, kneel facing away', 'Hold rope by your ears, curl your torso down toward thighs', 'Squeeze abs at the bottom, return with control'],
    tips: 'Don\'t use your arms to pull — the movement comes from your core. Curl like a ball.',
    commonMistakes: 'Using arms to pull, not curling enough, going too heavy.',
    duration: 40, rest: 45,
  },
  'Hanging Leg Raises': {
    type: 'crunch',
    muscles: ['Lower Abs', 'Hip Flexors'],
    difficulty: 'Intermediate',
    description: 'Hang from a bar and raise your legs to target lower abs.',
    steps: ['Hang from a pull-up bar with arms extended', 'Raise legs until they\'re parallel to floor (or higher)', 'Lower with control without swinging'],
    tips: 'Keep your legs straight. If that\'s too hard, bend your knees (knee raises).',
    commonMistakes: 'Swinging, using momentum, not lowering fully, arching back.',
    duration: 40, rest: 60,
  },
  'Russian Twists': {
    type: 'twist',
    muscles: ['Obliques', 'Core'],
    difficulty: 'Beginner',
    description: 'Sit and rotate your torso side to side, optionally holding a weight.',
    steps: ['Sit with knees bent, lean back slightly, feet off floor', 'Hold hands together or hold a weight', 'Rotate torso to one side, then the other', 'Keep core engaged throughout'],
    tips: 'Keep your back straight. Rotate from your torso, not just your arms.',
    commonMistakes: 'Rounding back, using arms only, moving too fast, holding breath.',
    duration: 40, rest: 45,
  },
  'Ab Wheel Rollouts': {
    type: 'hold',
    muscles: ['Core', 'Lower Back', 'Shoulders'],
    difficulty: 'Advanced',
    description: 'Roll an ab wheel forward and back using your core.',
    steps: ['Kneel on floor holding ab wheel handles', 'Roll wheel forward, extending your body', 'Go as far as you can control, then pull back using your core'],
    tips: 'Keep your core extremely tight. Don\'t let your hips sag. Go only as far as you can control.',
    commonMistakes: 'Sagging hips, going too far (back strain), using arms instead of core.',
    duration: 35, rest: 60,
  },
  'Treadmill Running': {
    type: 'cardio',
    muscles: ['Full Body', 'Cardiovascular'],
    difficulty: 'Beginner',
    description: 'Run on a treadmill at a steady pace.',
    steps: ['Start at a brisk walking pace to warm up', 'Increase speed to a comfortable running pace', 'Maintain good posture — look forward, relaxed shoulders'],
    tips: 'Land mid-foot. Keep a slight forward lean. Swing arms naturally.',
    commonMistakes: 'Holding the rails, overstriding, slouching, looking down.',
    duration: 20, rest: 0,
  },
  'Cycling': {
    type: 'cardio',
    muscles: ['Legs', 'Cardiovascular'],
    difficulty: 'Beginner',
    description: 'Cycle on a stationary bike at a steady pace.',
    steps: ['Adjust seat height so leg is nearly extended at bottom of pedal stroke', 'Start with low resistance, pedal at 80-100 RPM', 'Increase resistance for more intensity'],
    tips: 'Keep your core engaged. Don\'t slouch. Pedal in smooth circles.',
    commonMistakes: 'Resistance too low (spinning wildly) or too high (grinding), poor posture.',
    duration: 25, rest: 0,
  },
  'Jump Rope': {
    type: 'cardio',
    muscles: ['Full Body', 'Calves', 'Cardiovascular'],
    difficulty: 'Intermediate',
    description: 'Jump rope at a moderate pace for cardio.',
    steps: ['Hold rope handles at hip height', 'Swing rope overhead and jump as it passes under', 'Land softly on the balls of your feet', 'Keep jumping in a steady rhythm'],
    tips: 'Jump just high enough for the rope to clear. Land softly. Keep elbows close to body.',
    commonMistakes: 'Jumping too high, landing hard, elbows flared out.',
    duration: 15, rest: 0,
  },
  'Rowing Machine': {
    type: 'cardio',
    muscles: ['Full Body', 'Back', 'Legs', 'Arms'],
    difficulty: 'Beginner',
    description: 'Row on a machine using legs, back, and arms in sequence.',
    steps: ['Start with knees bent, arms extended, grip handle', 'Drive with legs first, then lean back and pull handle to lower ribs', 'Extend arms first, then hinge forward, then bend knees to slide forward'],
    tips: 'The power comes from your legs — 60% legs, 20% back, 20% arms.',
    commonMistakes: 'Pulling with arms first, rounding back, rushing the recovery.',
    duration: 20, rest: 0,
  },
  'HIIT Circuit': {
    type: 'cardio',
    muscles: ['Full Body', 'Cardiovascular'],
    difficulty: 'Advanced',
    description: 'Alternate between high-intensity exercise and rest.',
    steps: ['Choose exercises (burpees, sprints, etc.)', 'Go all-out for 30 seconds', 'Rest for 15-30 seconds', 'Repeat for 15-20 minutes total'],
    tips: 'Go as hard as possible during work intervals. Use active recovery during rest.',
    commonMistakes: 'Not going hard enough during work intervals, resting too long.',
    duration: 20, rest: 0,
  },
};

export const ANIMATION_TYPES = {
  push: {
    label: 'Pushing',
    description: 'Extend and retract arms in a pressing motion',
    getStyle: (phase) => ({
      transform: `translateY(${Math.sin(phase * Math.PI * 2) * -15}px) scaleY(${1 + Math.sin(phase * Math.PI * 2) * 0.1})`,
    }),
  },
  pull: {
    label: 'Pulling',
    description: 'Pull resistance toward your body',
    getStyle: (phase) => ({
      transform: `translateX(${Math.sin(phase * Math.PI * 2) * 15}px)`,
    }),
  },
  squat: {
    label: 'Squatting',
    description: 'Bend and extend your legs',
    getStyle: (phase) => {
      const val = Math.sin(phase * Math.PI * 2);
      return { transform: `translateY(${val * 20}px) scaleY(${1 + val * 0.08})` };
    },
  },
  hinge: {
    label: 'Hinging',
    description: 'Hinge at the hips',
    getStyle: (phase) => ({
      transform: `rotate(${Math.sin(phase * Math.PI * 2) * 20}deg)`,
    }),
  },
  fly: {
    label: 'Flying',
    description: 'Open and close arms in an arc',
    getStyle: (phase) => ({
      transform: `scaleX(${1 + Math.sin(phase * Math.PI * 2) * 0.2})`,
    }),
  },
  press: {
    label: 'Pressing',
    description: 'Press weight overhead',
    getStyle: (phase) => ({
      transform: `translateY(${Math.sin(phase * Math.PI * 2) * -18}px)`,
    }),
  },
  curl: {
    label: 'Curling',
    description: 'Curl weight toward shoulders',
    getStyle: (phase) => ({
      transform: `rotate(${Math.sin(phase * Math.PI * 2) * -60}deg)`,
      transformOrigin: 'center bottom',
    }),
  },
  raise: {
    label: 'Raising',
    description: 'Raise arms out or up',
    getStyle: (phase) => ({
      transform: `rotate(${Math.sin(phase * Math.PI * 2) * -45}deg)`,
    }),
  },
  hold: {
    label: 'Holding',
    description: 'Hold position steady',
    getStyle: (phase) => ({
      transform: `scale(${1 + Math.sin(phase * Math.PI * 2) * 0.02})`,
    }),
  },
  crunch: {
    label: 'Crunching',
    description: 'Curl torso forward',
    getStyle: (phase) => ({
      transform: `rotate(${Math.sin(phase * Math.PI * 2) * 25}deg)`,
      transformOrigin: 'center bottom',
    }),
  },
  twist: {
    label: 'Twisting',
    description: 'Rotate side to side',
    getStyle: (phase) => ({
      transform: `rotateY(${Math.sin(phase * Math.PI * 2) * 30}deg)`,
    }),
  },
  lunge: {
    label: 'Lunging',
    description: 'Step forward and lower',
    getStyle: (phase) => {
      const val = Math.sin(phase * Math.PI * 2);
      return { transform: `translateX(${val * 12}px) translateY(${Math.abs(val) * -10}px)` };
    },
  },
  cardio: {
    label: 'Cardio',
    description: 'Continuous rhythmic movement',
    getStyle: (phase) => ({
      transform: `translateY(${Math.sin(phase * Math.PI * 4) * -8}px) rotate(${Math.sin(phase * Math.PI * 2) * 10}deg)`,
    }),
  },
};

export function getAnimationType(exerciseName) {
  const detail = EXERCISE_DETAILS[exerciseName];
  return detail?.type || 'generic';
}
